# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
calculator:
  url:   /
  param: { module: calculator, action: calculator}

calculator_add:
  url:  /add/:number_a/:number_b
  param: { module: calculator, action: add}

calculator_sub:
  url:  /sub/:number_a/:number_b
  param: { module: calculator, action: sub}

calculator_mul:
  url:  /mul/:number_a/:number_b
  param: { module: calculator, action: multiply}

calculator_div:
  url:  /div/:number_a/:number_b
  param: { module: calculator, action: divide}

